import { Header } from "@/src/components/Header";
import "./globals.css";
import { Footer } from "@/src/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        <Header />
        <main className="min-h-screen bg-background flex flex-col items-center">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
